// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8__d3vswsjNUSYMuTPPSARLO2vDsdBWk',
    appId: '1:447775354482:web:c35e1ae747dbfd01a91ceb',
    messagingSenderId: '447775354482',
    projectId: 'beutonomi',
    authDomain: 'beutonomi.firebaseapp.com',
    storageBucket: 'beutonomi.appspot.com',
    measurementId: 'G-38YTDQ9PRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx71EnfXyvIt_AxGXaenuz0w_Rsrvy2rU',
    appId: '1:447775354482:android:70cce29678effc47a91ceb',
    messagingSenderId: '447775354482',
    projectId: 'beutonomi',
    storageBucket: 'beutonomi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUmUXw_epTWJiWPLW8iYKnLUPcPVt_w4M',
    appId: '1:447775354482:ios:621ae175a04f3c4da91ceb',
    messagingSenderId: '447775354482',
    projectId: 'beutonomi',
    storageBucket: 'beutonomi.appspot.com',
    iosClientId: '447775354482-0flf5vu6v41tkag40n1icbe9p03d54ni.apps.googleusercontent.com',
    iosBundleId: 'com.app.beautonomi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUmUXw_epTWJiWPLW8iYKnLUPcPVt_w4M',
    appId: '1:447775354482:ios:621ae175a04f3c4da91ceb',
    messagingSenderId: '447775354482',
    projectId: 'beutonomi',
    storageBucket: 'beutonomi.appspot.com',
    iosClientId: '447775354482-0flf5vu6v41tkag40n1icbe9p03d54ni.apps.googleusercontent.com',
    iosBundleId: 'com.app.beautonomi',
  );
}
